# Generated by Django 2.2 on 2020-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200302_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
